# Autogenerated file
def render(version, latest):
    yield """

<!DOCTYPE html>
<html lang=\"en\">
    """
# Autogenerated file
    def render1(*a, **d):
        yield """ <head>
    <meta charset=\"utf-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <link rel=\"stylesheet\" type=\"text/css\" href=\"/static/styles.css\" />
    <title>Whatnick: Energy Monitor</title>
</head>"""
    yield from render1()
    yield """
	<body>
       """
# Autogenerated file
    def render2(*a, **d):
        yield """<div class=\"masthead\">
    <a href=\"/\">
        
    </a>
</div>"""
    yield from render2()
    yield """
         <div class=\"pagesection\">
            <div class=\"component\">
                """
# Autogenerated file
    def render3(title):
        yield """

<div class=\"ui__header\">
    <h1 class=\"heading\">"""
        yield str(title)
        yield """</h1>
    <nav class=\"controls\">
    <a href=\"/\" class=\"btn_close\">
    <svg class=\"icon\" width=\"30\" height=\"30\">
       <path d=\"M15.707,15l3.625-3.624c0.194-0.195,0.194-0.512,0-0.707c-0.195-0.195-0.513-0.195-0.707,0L15,14.293l-3.624-3.625
	c-0.195-0.195-0.512-0.195-0.707,0s-0.195,0.512,0,0.707L14.293,15l-3.625,3.625c-0.195,0.194-0.195,0.512,0,0.707
	c0.098,0.096,0.226,0.146,0.354,0.146s0.256-0.05,0.354-0.146L15,15.707l3.625,3.625c0.098,0.098,0.226,0.146,0.354,0.146
	s0.254-0.05,0.352-0.146c0.195-0.195,0.195-0.513,0-0.707L15.707,15z\"/>
    </svg>
    close</a>
    </nav>
</div>"""
    yield from render3('Firmware')
    yield """
                <div class=\"ui__body\">
                    <div class=\"content\">
                        <h3>Version</h3>
                        <table>
                            <tr><td>Installed firmware version</td><td>"""
    yield str(version)
    yield """</td></tr>
                            <tr><td>Latest stable firmware version</td><td>"""
    yield str(latest)
    yield """</td></tr>
                        </table>
                        <p>[ Device notes + Firmware upgrade notes... ]</p>
                    </div>
                    <form class=\"form form__firmaware\">
                        <p><button>Install firmware</button></p>
                    </form>
                </div>
            </div>
        </div>
       """
# Autogenerated file
    def render4(*a, **d):
        yield """<script src=\"/static/vendor/vue_development.js\"></script>"""
    yield from render4()
    yield """
	</body>
</html>"""
