# Autogenerated file
def render(thingspeak, awsiot, active_logger):
    yield """

<!DOCTYPE html>
<html lang=\"en\">
    """
# Autogenerated file
    def render1(*a, **d):
        yield """ <head>
    <meta charset=\"utf-8\">
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
    <link rel=\"stylesheet\" type=\"text/css\" href=\"/static/styles.css\" />
    <title>Whatnick: Energy Monitor</title>
</head>"""
    yield from render1()
    yield """
	<body>
       """
# Autogenerated file
    def render2(*a, **d):
        yield """<div class=\"masthead\">
    <a href=\"/\">
        
    </a>
</div>"""
    yield from render2()
    yield """
        <div id=\"vue_app\" class=\"pagesection\">
            <div  class=\"component\">
                """
# Autogenerated file
    def render3(title):
        yield """

<div class=\"ui__header\">
    <h1 class=\"heading\">"""
        yield str(title)
        yield """</h1>
    <nav class=\"controls\">
    <a href=\"/\" class=\"btn_close\">
    <svg class=\"icon\" width=\"30\" height=\"30\">
       <path d=\"M15.707,15l3.625-3.624c0.194-0.195,0.194-0.512,0-0.707c-0.195-0.195-0.513-0.195-0.707,0L15,14.293l-3.624-3.625
	c-0.195-0.195-0.512-0.195-0.707,0s-0.195,0.512,0,0.707L14.293,15l-3.625,3.625c-0.195,0.194-0.195,0.512,0,0.707
	c0.098,0.096,0.226,0.146,0.354,0.146s0.256-0.05,0.354-0.146L15,15.707l3.625,3.625c0.098,0.098,0.226,0.146,0.354,0.146
	s0.254-0.05,0.352-0.146c0.195-0.195,0.195-0.513,0-0.707L15.707,15z\"/>
    </svg>
    close</a>
    </nav>
</div>"""
    yield from render3('Logging service')
    yield """
                <div 
                    class=\"ui__body ani_height\" 
                    :style=\""""
    yield """{ height: formheight }\"
                    v-on:transitionend=\"ani_end\"
                >
                    <form ref=\"vform\" class=\"form form__logging\" method=\"post\">
                        <fieldset>
                            <p>
                                <label>
                                    Logging service
                                    <select 
                                        name=\"service\"
                                        v-model=\"service\"
                                        v-on:change=\"ani_start\"
                                    >
                                        <option"""
    if active_logger == '':
        yield """ selected"""
    yield """ value=\"\">-- No service selected --</option>
                                        <option"""
    if active_logger == 'thingspeak':
        yield """ selected"""
    yield """ value=\"thingspeak\">"""
    yield str(thingspeak['name'])
    yield """</option>
                                        <option"""
    if active_logger == 'awsiot':
        yield """ selected"""
    yield """ value=\"awsiot\">"""
    yield str(awsiot['name'])
    yield """</option>
                                    </select>
                                </label>
                            </p>
                        </fieldset>
                        <fieldset """
    if active_logger != 'thingspeak':
        yield """ v-cloak """
    yield """ v-if=\"service=='thingspeak'\">
                        <h3>ThingSpeak</h3>
                            <p>
                                <label>
                                    API Key <input name=\"ts_key\" type=\"text\" value=\""""
    yield str(thingspeak['key'])
    yield """\">
                                </label>
                            </p>
                        </fieldset>
                        <fieldset  """
    if active_logger != 'awsiot':
        yield """ v-cloak """
    yield """ v-if=\"service=='awsiot'\">
                            <h3>Amazon web service, IoT</h3>
                            <p>
                                <label>
                                    Certificate <input name=\"cert\" type=\"file\" value=\""""
    yield str(awsiot['cert'])
    yield """\">
                                </label>
                            </p>
                            <p>
                                <label>
                                    Private key <input name=\"aws_key\" type=\"file\" value=\""""
    yield str(awsiot['key'])
    yield """\">
                                </label>
                            </p>
                            <p>
                                <label>
                                    Endpoint subdomain <input name=\"subdomain\" type=\"text\" value=\""""
    yield str(awsiot['subdomain'])
    yield """\">
                                </label>
                            </p>
                            <p>
                                <label>
                                    Endpoint region <input name=\"region\" type=\"text\" value=\""""
    yield str(awsiot['region'])
    yield """\">
                                </label>
                            </p>
                        </fieldset>
                        <p>
                            <a class=\"button\" href=\"/\">Cancel</a> 
                            <button name=\"submit\" type=\"submit\">Save</button>
                        </p>
                    </form>
                </div>
            </div>
        </div>
        """
# Autogenerated file
    def render4(*a, **d):
        yield """<script src=\"/static/vendor/vue.min.js\"></script>"""
    yield from render4()
    yield """
        <script>
            var active_logger = \""""
    yield str(active_logger)
    yield """\"
        </script>
        <script src=\"/static/logging.js\"></script>
	</body>
</html>"""
